package com.specification.repo;

import com.specification.entities.Role;
import com.specification.entities.User;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

@DataJpaTest
public class UserRepositoryTest {

    @Autowired
    private UserRepo userRepo;

    @Test
    @DisplayName("When save user checking if id is autogenerated or not")
    public void saveUser() {
        Role mockAdminRole = new Role(2, "admin");
        User mockUser = new User(0, "suraj@gmail.com", "Suraj Verma", 28, mockAdminRole, null);
        User userSaved = userRepo.save(mockUser);
        Assertions.assertThat(userSaved.getId()).isGreaterThan(0);
    }
}
